### ISSUE TITLE
Code Request for the paper.

### ISSUE THREAD

**Issue by kanseaveg** [Laqcce-cao/RSL-SQL#1]
Hi. I'm really interesting in your paper. When do you plan to release the source code?

**Comment by Laqcce-cao** [comment]
Thank you for your support, I am refactoring my code and I will upload my code and data within a week.

**Comment by deniswsrosa** [comment]
Nice! Looking forward to it as well

**Comment by Laqcce-cao** [comment]
I have uploaded my code, thank you for your support, I hope my code can inspire you.

**Comment by kanseaveg** [comment]
Thank you for your contributions to the Text-to-SQL community; I can't wait to start researching.

**Comment by kanseaveg** [comment]
BTW, could you please let me know the token costs for this code during inference and training?

**Comment by Laqcce-cao** [comment]
Of course, it takes about 20 million in total. Using the deepseek model, it spent less than one dollar。

**Comment by kanseaveg** [comment]
Okay, thank you for your patience in answering, I will try it.
