### ISSUE TITLE
Question:"python src/data_construct.py" KeyError: ppl['evidence']

### ISSUE THREAD

**Issue by JarvenYi** [Laqcce-cao/RSL-SQL#2]
run `python src/data_construct.py`
Error:
```
File "***/RSL-SQL-main/src/data_construct.py", line 41, in creat_output_structure
    evidence = ppl['evidence']
KeyError: ppl['evidence']
```

**Comment by JarvenYi** [comment]
Resolved.
Cause of the error: The input data was Spider1.0, which did not match the code configuration.
Modification: Ensured that the input data is the BIRD dataset.

**Comment by Laqcce-cao** [comment]
The Spider-related code is in "main_result" folder.

Hope my code can bring you some help.
