### ISSUE TITLE
Help Wanted! Questions about these files during reproduction.

### ISSUE THREAD

**Issue by kanseaveg** [Laqcce-cao/RSL-SQL#3]
![image](https://github.com/user-attachments/assets/f282600c-a681-4c4c-b52a-636d137c1329)

I have questions about the README.md file description when reproducing on the bird dataset. The format of the bird dataset is as follows.

![image](https://github.com/user-attachments/assets/22ad513d-1e79-4d3d-80c8-9ea2ae50dacc)
Which one is the real test.json, which one is the real test_tables.json, and which dev.json is needed for the few_shot folder?

What files are needed for the evaluation of the bird-dev set? thank you.

**Comment by kanseaveg** [comment]
BTW.

The [dev.json](https://github.com/Laqcce-cao/RSL-SQL/blob/main/few_shot/dev.json) in the repository is very strange, as it is exactly the same as the dev.json in the bird-dev dataset.  In theory, if placed under the few_shot folder, it should have a few-shot Prompt? It seems that the significance of introducing the original dev.json file here is not well understood.


What's even stranger is that in the [construct_QA.py](https://github.com/Laqcce-cao/RSL-SQL/blob/main/few_shot/construct_QA.py), I found a repetitive and incomprehensible logic where the file is repeatedly read and assigned to the same field. 

![image](https://github.com/user-attachments/assets/94dae845-bd90-4c29-af29-bc577d06249d)

I hope you can answer my question.

**Comment by Laqcce-cao** [comment]
Oh no, I'm very sorry. It was my negligence that caused you to have such a question. 

 This is the **readme.md** file that I submitted to the BIRD official for testing, so files such as **text.json** will appear, as well as the operation of extracting few-shot examples from **dev.json**.  

I once again expressed my apology and immediately revised my documentation.

**Comment by kanseaveg** [comment]
Okay, I figured as much. Thank you for your response.
