### ISSUE TITLE
Help Wanted! Question about the process of example selection.

### ISSUE THREAD

**Issue by kanseaveg** [Laqcce-cao/RSL-SQL#4]
![image](https://github.com/user-attachments/assets/6c6d1ac0-9d7b-4810-a386-1e6dafba28fe)

When selecting examples, I found that the validation set dev.json was also included in train_embeddings, which would result in each example taken from dev.json being the embeddings represented by that question. Is this approach problematic? Could the improvements observed in the ablation experiments of the paper be attributed to this effect?
![image](https://github.com/user-attachments/assets/24dd65e3-bf9b-40e3-8099-0058eb36197e)

**Comment by Laqcce-cao** [comment]
Your previous question asked me why dev.json was placed in the few-shot folder. I would like to know if you have reconstructed the question-answer pair.

**Comment by kanseaveg** [comment]
I have already constructed the question-answer pairs.
![image](https://github.com/user-attachments/assets/67b29786-bc0b-455a-adb9-66efa0a333a1)

This will generate QA.json


There is definitely an issue with the code here. If cu is set to 1 in construct_QA.py or left as the default, it will encode questions from dev.json into train_embeddings, leading to situations where using questions from dev.json to retrieve examples results in the first few-shot example being from dev.json itself. This causes subsequent preSQL generation to produce answers almost identical to the ground truth.

```
python src/step_1_preliminary_sql.py --ppl_file src/information/ppl_dev.json --sql_out_file src/sql_log/preliminary_sql.txt --Schema_linking_LLM src/schema_linking/LLM.json --start_index 0
```

**Comment by Laqcce-cao** [comment]
Thanks for your question.

I'm pretty sure I didn't use the validation set's question-answer pairs as context, which would be an information leak, and I understand the dangers and risks of doing so.

Secondly, if we use question and answer pairs as context examples, our execution accuracy cannot be just around 62%. I suggest you delete dev.json from the few-shot/ folder and try again to see if this happens again.

I was very shocked by the huge gain of few-shot examples, so I checked this area strictly.

If you still have questions, please contact me in time.

**Comment by kanseaveg** [comment]
![image](https://github.com/user-attachments/assets/8ecff6bf-7542-45a0-b639-42507aed753a)
![image](https://github.com/user-attachments/assets/df86f9fa-ad68-4176-adbc-525b51bf07de)

What happened? Did you just delete the `construct_qa.py`?

**Comment by Laqcce-cao** [comment]
Yes, I deleted the ambiguous part of the code. This part of the code was for BIRD official testing, so that there is no problem with the cu field.

**Comment by kanseaveg** [comment]
If it was deleted here an hour ago, there would indeed be no information leak issue. I just had a question while reviewing your code, so I'm confirming with you.
Additionally, the method of selecting examples used here is derived from the approach in DAIL-SQL?

**Comment by Laqcce-cao** [comment]
Yes, the DAIL-SQL paper is the second paper I saw in text2SQL, and it has a great influence on me. I was shocked that few-shot had such a big impact.

**Comment by kanseaveg** [comment]
Awesome, but why didn't you adopt a skeleton-based approach for further similarity measurement instead of using a question Mask method?
I remember that the former performed better than the latter in DAIL-SQL, right?

**Comment by kanseaveg** [comment]
To be honest, I believe that RSL's paper is a further supplement to DAIL-SQL in terms of principles, at least in the areas of few-shot selection and skeleton generation. The subsequent refinement and correction process was observed in my recent community research and peer review, which is commonly seen in most articles on LLM-based NL2SQL. As for bidirectional linking and bidirectional SQL selection, I think it might be due to some randomness and intrinsic factors within the LLM, and based on ablation studies, it seems that both contribute to an increase of around 4 points in scores.

![image](https://github.com/user-attachments/assets/3e3b27c4-527f-4682-bda8-2f0697af1ba8)

Of course, this is not a rebuttal, I am merely expressing my opinion. Please do not hold it against me; you may also try to express your thoughts. thank you.

**Comment by Laqcce-cao** [comment]
Yes, you are right. After listening to your comments, I think you have a very deep understanding of text2SQL.

This skeleton-based approach is indeed more effective than just based on similarity, but due to time constraints, I haven't had time to do it yet.

It can also be seen that there are very few examples of few-shot examples used in our work, and there is no SQL candidate pool. There is still a lot of room for optimization, and I will gradually improve it next.

Thank you for your question, it helps further improve our work.

**Comment by kanseaveg** [comment]
> Yes, you are right. After listening to your comments, I think you have a very deep understanding of text2SQL.
> 
> This skeleton-based approach is indeed more effective than just based on similarity, but due to time constraints, I haven't had time to do it yet.
> 
> It can also be seen that there are very few examples of few-shot examples used in our work, and there is no SQL candidate pool. There is still a lot of room for optimization, and I will gradually improve it next.
> 
> Thank you for your question, it helps further improve our work.

Thank you very much for your contributions to the community and for releasing the source code so promptly. I hope it gets accepted by a good conference or journal.

**Comment by Laqcce-cao** [comment]
Thank you for your blessings and I wish you smooth sailing on your research path.

**Comment by kanseaveg** [comment]
BTW. I found another issue in the code: The paper claims that the full schema is used when generating preSQL, but in the code and prompts, it appears that you are filtering relevant tables and columns to further enhance SQL generation, which contradicts the meaning expressed in the paper.

This is the first example, generating the prompt for preSQL1.




"""
'role': 'user', 'content': "### Some example pairs of question and corresponding SQL query are provided based on similar problems:\n\n### What is the average total donations received by Fresno County colleges?\nSELECT SUM(T2.donation_optional_support + T2.donation_to_project) / COUNT(donationid) FROM projects AS T1 INNER JOIN donations AS T2 ON T1.projectid = T2.projectid WHERE T1.school_county = 'Fresno'\n\n### How many schools in the West New York School District have the highest poverty level?\nSELECT COUNT(poverty_level) FROM projects WHERE school_district = 'West New York School District' AND poverty_level = 'highest poverty'\n\n### In which city is there a greater number of schools that have received donations of less than 10 dollars?\nSELECT T2.school_city FROM donations AS T1 INNER JOIN ...
...
`OpenDate`, `ClosedDate`, `Charter`, `CharterNum`, `FundingType`, `DOC`, `DOCType`, `SOC`, `SOCType`, `EdOpsCode`, `EdOpsName`, `EILCode`, `EILName`, `GSoffered`, `GSserved`, `Virtual`, `Magnet`, `Latitude`, `Longitude`, `AdmFName1`, `AdmLName1`, `AdmEmail1`, `AdmFName2`, `AdmLName2`, `AdmEmail2`, `AdmFName3`, `AdmLName3`, `AdmEmail3`, `LastUpdate`)\n#\n### Here are some data information about database references.\n#\n# frpm(`CDSCode`[01100170109835,01100170112607,01100170118489],`Academic Year`[2014-2015,2014-2015,2014-2015],`County Code`[01,01,01],`District Code`[10017,10017,10017],`School Code`[0109835,0112607,0118489],
...
AdmFName3`[None,None,None],`AdmLName3`[None,None,None],`AdmEmail3`[None,None,None],`LastUpdate`[2015-06-23,2015-09-01,2015-06-18]);\n#\n### Foreign key information of Sqlite SQL tables, used for table joins:\n#\n# frpm(CDSCode) references schools(CDSCode)\n# satscores(cds) references schools(CDSCode)\n**#### tables: ['frpm', 'schools']\n### columns: ['frpm.`CDSCode`', 'frpm.`Free Meal Count (K-12)`', 'frpm.`Enrollment (K-12)`', 'schools.`County`', 'schools.`School`']\n\n### definition: Eligible free rate for K-12 = `Free Meal Count (K-12)` / `Enrollment (K-12)`\n**### Question: What is the highest eligible free rate for K-12 students in the schools in Alameda County?"
"""



![image](https://github.com/user-attachments/assets/50a1576f-e044-4c2e-8f5f-00c16d961808)

```python
**# try to get relevant table and columns**
def table_column_selection(table_info, ppl):
    gpt = model()
    evidence = ppl['evidence'].strip()
    question = ppl['question'].strip()
    prompt_table = table_info.strip() + '\n\n' + '### definition: ' + evidence + "\n### Question: " + question
    table_column = gpt(TABLE_AUG_INSTRUCTION, prompt_table)
    table_column = json.loads(table_column)
    return table_column


def preliminary_sql(table_info, table_column, ppl):
    gpt = model()
    example = ppl['example']
    evidence = ppl['evidence'].strip()
    question = ppl['question'].strip()
    table_info += f'### tables: {table_column["tables"]}\n'
    table_info += f'### columns: {table_column["columns"]}\n'

    table_info = example.strip() + "\n\n### Answer the question by sqlite SQL query only and with no explanation. You must minimize SQL execution time while ensuring correctness.\n" + table_info.strip() + '\n\n### definition: ' + evidence + "\n### Question: " + question

    answer = gpt(SQL_GENERATION_INSTRUCTION, table_info)
    try:
        answer = json.loads(answer)
    except Exception as e:
        print(e)
        answer = answer.replace("\\", "\\\\")
        answer = json.loads(answer)
    answer = answer['sql'].replace('\n', ' ')
    return answer


def main(ppl_file, output_file, info_file, x=0):
    with open(ppl_file, 'r', encoding='utf-8') as f:
        ppls = json.load(f)

    answers = []
    informations = []

    for i in tqdm(range(x, len(ppls))):
        information = {}
        ppl = ppls[i]

        # table_info
        table_info = table_info_construct(ppl)

        #  table_column : which get the relevant tables and columns
        **table_column = table_column_selection(table_info, ppl)**
        information['tables'] = table_column['tables']
        information['columns'] = table_column['columns']
        informations.append(information)

        # preliminary_sql : Using relevant S to generate SQL1 which is not consistent with the paper described.
        pre_sql = preliminary_sql(table_info, **table_column**, ppl)
        answers.append(pre_sql)
```

**Comment by Laqcce-cao** [comment]
Not really. Instead of filtering out irrelevant columns, I use the selected relevant columns and add them to the prompt as some additional information. The complete schema is still used.
<img width="628" alt="image" src="https://github.com/user-attachments/assets/21e75007-cba9-4a51-8818-a7e9d15b7bb1">

**Comment by kanseaveg** [comment]
![image](https://github.com/user-attachments/assets/2a131338-ef93-45cc-bf5d-4d5fa352add9)
Upon closer inspection, it seems I misunderstood the meanings of "**filtering**" and "**selection**." So what you're saying here is: preserve the original full schema, select key columns, mark these key columns, guide the model to focus on them, and finally execute SQL generation.



To be honest, if you don't look closely, you really wouldn't notice this sentence.
![image](https://github.com/user-attachments/assets/86b1bac2-638c-4d19-8492-6ec4ffb374a0)
