### ISSUE TITLE
Last Question Help Wanted! Discrepancy between bidirectional schema linking code and paper

### ISSUE THREAD

**Issue by kanseaveg** [Laqcce-cao/RSL-SQL#5]
I have reviewed all the code, but I have questions about the differences between the implementation in the code and what is described in the paper regarding bidirectional schema linking. I understand that this approach is actually equivalent.

### In The Code
In `bid_schema_linking.py`, you extract the tables and columns mentioned in preSQL1 by comparing it with both the full dbschema and hint, as well as by comparing hint with preSQL1.
https://github.com/Laqcce-cao/RSL-SQL/blob/ecee46ffee3ad22ffae3edb5072e43286db0fb31/src/bid_schema_linking.py#L32-L70
https://github.com/Laqcce-cao/RSL-SQL/blob/ecee46ffee3ad22ffae3edb5072e43286db0fb31/src/bid_schema_linking.py#L74-L117

### In The  Paper
![image](https://github.com/user-attachments/assets/43fb0b05-581d-4e16-93fe-b39e797cda93)

### Question
1. In the paper, it is mentioned that sqlglot is used to extract table columns. However, in the code, I only see sqlglot being used during the evaluation of linking, but not in bid_schema_linking.py. Can I consider these two approaches equivalent?
2. BTW. Another issue, upon reading the code logic, it seems that the following piece of code has no effect?
https://github.com/Laqcce-cao/RSL-SQL/blob/ecee46ffee3ad22ffae3edb5072e43286db0fb31/src/bid_schema_linking.py#L152-L199

I should not have any other questions, looking forward to your reply again. thank you.

**Comment by Laqcce-cao** [comment]
Thank you very much for your question.

1. Our paper has been updated to the second version. It seems that you are viewing the first version.
<img width="559" alt="image" src="https://github.com/user-attachments/assets/f0f56f21-4543-4a38-a2fe-5609ec909a01">

3. The filter() method is designed to control the case of column names and filter out some repeated elements.

We hope our approach is inspiring to you.

**Comment by kanseaveg** [comment]
Okay. Thank you.

![image](https://github.com/user-attachments/assets/380ffd17-8b70-4b02-9be3-e63871b9c964)

BTW, **why isn't the result of CHASE-SQL included in your latest revised paper?** I noticed that Chase is currently ranked first on the bird leaderboard. Moreover, as far as I know, the paper "CHASE-SQL" has already applied for ICLR 2025 and received high scores (8/5/6/6), with a high likelihood of being accepted.
![image](https://github.com/user-attachments/assets/d5e1e55d-2d59-49c0-aff9-f5a71638a5e1)
