### ISSUE TITLE
How the column_meaning.json is generated? 

### ISSUE THREAD

**Issue by YjyJeff** [Laqcce-cao/RSL-SQL#6]
Hi, I do not find the code to generate the `column_meaning.json`, how do you generate it from the bird description files?

I want to generate it such that other datasets could also use the description info.

**Comment by Laqcce-cao** [comment]
This is due to some information that comes with the bird database. This TA-SQL article has structured it. If you want to use these descriptions, you can also let LLM generate them, but the cost is relatively high. For specific details, please refer to https://arxiv.org/abs/2405.15307
