### ISSUE TITLE
preliminary sql generation

### ISSUE THREAD

**Issue by JackMeiLong** [Laqcce-cao/RSL-SQL#7]
请问preliminary sql 是基于什么内容生成的？

**Comment by Laqcce-cao** [comment]
preliminary sql is based on few-shot examples，  full database schema，value samples，the result of forward schema linking， question， and evidence.

**Comment by JackMeiLong** [comment]
ppl_dev.json 是否可以提供一个 demo？

**Comment by Laqcce-cao** [comment]
of course
[ppl_dev.json](https://github.com/user-attachments/files/18105139/ppl_dev.json)
